# Generated by Django 2.2.9 on 2020-02-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='arrival_time',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='destination',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='plate',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='special',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='volume',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
