# Generated by Django 2.2.9 on 2020-02-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20200203_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='driver',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='sharer',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
