# Generated by Django 2.2.9 on 2020-02-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20200203_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='arrival_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='plate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='special',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='volume',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
