# Generated by Django 2.2.9 on 2020-02-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200205_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='volume',
            field=models.CharField(max_length=30),
        ),
    ]
