# Generated by Django 2.2.9 on 2020-02-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200207_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_dest',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_volume',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
